### ISSUE TITLE
SUPER large algos crash chrome tab

### ISSUE THREAD

**Issue by hchaudhary1** [nocode-js/sequential-workflow-designer#107]
This is a real algo -- it takes up about 1.1GB of ram on chrome.
It is very difficult to navigate and edit.
What can be done to increase the responsiveness?

https://dev.algozen.io/share_page/2d27a53da98021ee05afa4f3c70f5ec24bc591b4b15e91bb56a4c56359ac467d

**Comment by b4rtaz** [comment]
Hello @hchaudhary1!

Wow, this algorithm is huge. I thought that the [stress test](https://nocode-js.github.io/sequential-workflow-designer/examples/stress-test.html) example is big, but your example is bigger (2871 steps). 😅

I think the main problem is not the designer but your design overall. Even if the designer would be better optimized and use less memory, then still with that many elements on the canvas the user experience would be poor.

I think you need a way to apply the "[don't repeat yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)" principle by your users. You can achieve that in many ways like creating a way to reuse a logic. For example you can create a step that executes another flow.

Another way is to move conditions at the step level, in [this example](https://nocode-js.github.io/sequential-workflow-designer/examples/multi-conditional-switch.html) you can see that, each branch has own "condition". It's a simple string but it could be a complex editor. Additionaly check [this example](https://nocode-js.github.io/sequential-workflow-editor/webpack-app/public/playground.html).

Also, you could use the [folder step component](https://nocode-js.com/docs/sequential-workflow-designer/step-components/folder) to group some parts of your logic.

**Comment by hchaudhary1** [comment]
Thanks for reviewing this. Our users are not programers unfortunately, and didn't understand the concept of functions, instead they just copy-paste the logic everywhere. Perhaps we can run a script that automatically groups the sub-routines.

A few follow-up questions:
1. Folders -- The JSON will still stay very large. Is the slowness due to large JSON or is it due to graphics rendering?
2. Any hope to offload rendering to WebGL for better speed?
3. Here is a zoom-in of the canvas... what do you mean by "move conditions at the step level"?
<img width="1241" alt="Screenshot 2023-12-18 at 11 29 12 PM" src="https://github.com/nocode-js/sequential-workflow-designer/assets/7873717/d82bca1b-cb7d-4ecb-aeb5-e0306cdb3639">

**Comment by b4rtaz** [comment]
1. I suppose the cause is a large amount of HTML nodes in the DOM. The designer is not responsible directly for rendering, it generates the DOM structure by using SVG and CSS. So less elements = faster rendering.

2. I don't see any chance at the moment. This would completely change the way how the designer works.

3. You as a designer can design how steps look like. For example you can enforce users to use the switch step instead hierarchical conditions (check this [example](https://nocode-js.github.io/sequential-workflow-designer/examples/multi-conditional-switch.html)). 

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/12797776/c18bda4d-b910-40a4-a22c-40bdfef91ed7)

For example you may limit depth of conditions.

Or maybe this executing logic may be placed inside a single step. This don't have be a graphical structure inside the canvas.

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/12797776/0d5103d3-17d0-4f6c-be78-6962f9a3647b)

Another idea is to prepare a template with folders for main branches. This will cause users to continue with the proposed split.

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/12797776/1b391e62-faba-4f13-ae19-d0cf7d4c5705)

Generally speaking it's very important how you design your steps and the initial template.

**Comment by hchaudhary1** [comment]
Folders seem like the way to go. Thanks. Closing for now
