### ISSUE TITLE
Is it possible to interact with transitions

### ISSUE THREAD

**Issue by aruizca** [nocode-js/sequential-workflow-designer#17]
Hi there!

1st of all congrats for your work. It looks amazing and clean!

I have a questions regarding the transitions between workflow states, that would be the lines that connect the steps in your case. I'd like to know if they could be selectable and then apply a name to them.

Imaging the following example. I have a simple approval workflow with two states (steps in your case): In "Review" and "Approved". The line connecting both states is a transition called 'approve' which I need to be reflected in the diagram and interact with it (eg: onclick, ...)

Thanks a lot for your time!

**Comment by b4rtaz** [comment]
Hello @aruizca!

The designer doesn't support the naming for connecting lines, because basically we have just one transition type here, in general from top to bottom (this is similar to programming languages). So by design we don't want to name them because everyone knows the flow's direction.

Maybe you are looking a different component or you can rename your states into a more executive style.

<img width="273" alt="image" src="https://user-images.githubusercontent.com/12797776/211904847-63071245-e0a3-4041-b8b0-c52c7b441d88.png">

**Comment by aruizca** [comment]
Hi @b4rtaz 

Here is the kind of workflow I am talking about. For usability purposes we need to display the name of the transition:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/246477/211932736-0459d64d-0986-48e6-83f6-6b30431f5040.png">

Otherwise it is not really self explanatory. Do you think we could represent a similar workflow with your tool? If not now, maybe in the future?

Cheers!

**Comment by b4rtaz** [comment]
I think you need a different type of the designer than the SWD. Some time ago I created the [SVG Workflow Designer](https://github.com/b4rtaz/svg-workflow-designer) and I think it is closer to your needs. Check [this example](https://b4rtaz.github.io/svg-workflow-designer/examples/fullscreen.html). But this project has been suspended. I can unfreeze it if you want (please [contact me](https://n4no.com/)).

Otherwise you can try to adjust your flow to the SWD.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/12797776/211939315-52dd63d2-fc2a-4b68-b72e-9eaa4677b2a1.png">
