### ISSUE TITLE
package 'sequential-workflow-designer' not found

### ISSUE THREAD

**Issue by talboren** [nocode-js/sequential-workflow-designer#82]
https://www.npmjs.com/package/sequential-workflow-designer

**Comment by b4rtaz** [comment]
Hello @talboren!

Thanks for reporting. I unintentionally unpublished all versions of the designer from the NPM repository. Probably, that happened because the NPM CLI has a bug.

* I've sent a ticket to the NPM support. No response so far.
* I created an [issue](https://github.com/npm/cli/issues/6786) in the NPM CLI repository. No response so far.

It's Sunday, so a response may be delayed. We need to wait.

**Comment by talboren** [comment]
Thank you for the quick response!

**Comment by b4rtaz** [comment]
I'm not sure if will be possible to revert unpublished packages. I still didn't get a response from the NPM support. But here is a workaround:

### Workaround

I've just republished 4 minor versions of the designer and React/Angular packages. So please update your dependency to responding minor version. Here is a [list of all available versions](https://www.npmjs.com/package/sequential-workflow-designer?activeTab=versions).

```
0.10.x -> 0.10.3
0.13.x -> 0.13.8
0.14.x -> 0.14.2
0.15.x -> 0.15.2
```

For example if you are using:
```json
"sequential-workflow-designer": "^0.13.2",
"sequential-workflow-designer-react": "^0.13.2",
```
you need to bump versions to:
```json
"sequential-workflow-designer": "^0.13.8",
"sequential-workflow-designer-react": "^0.13.8",
```

**Comment by talboren** [comment]
@b4rtaz appreciate that. Thank you! hope you'll get to revert your changes ASAP 🙏🏼

**Comment by b4rtaz** [comment]
I've got a response from the support.

> Unfortunately, there is no way to re-use a version of a package in the npm registry, even if it's been unpublished - and we are unable to recover those versions.

That means the previous versions won't return. Every project needs to apply the workaround.
